### ISSUE TITLE
Don't pipe errors to /dev/null

### ISSUE THREAD

**Issue by mteam88** [x86Cow/CyberPatriotAutomationScript#3]
don't pipe the errors, we will want to see any errors that come up

**Comment by x86Cow** [comment]
In most cases I agree with this, although when using find some out put is considered errors such as permission denied. I might add a flag to pipe those errors out, and for apt errors.

**Comment by x86Cow** [comment]
Especially when writing the code on a machine that I know will work, the output can get quite annoying quite quickly.

**Comment by mteam88** [comment]
Hmm. Okay. I see the point of this, apt usually doesn't complain unnecessarily.

**Comment by x86Cow** [comment]
Apt usually outputs a lot of unnecessary information such as updates on pulling sources and etc, when reading the script's output I'd rather it be less output and more clean. Eventually I will make options to view everything but until then I want it clean and easy for development.

**Comment by mteam88** [comment]
You misunderstand me. We can pipe the regular output (stdout) to /dev/null, but any errors (stderr) should be shown. This is common practice in automation scripts. We will want to see any permission denied errors.

**Comment by x86Cow** [comment]
Alright I'll change it, hold up
